# Generated by Django 3.1.4 on 2021-03-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ecommerce", "0002_auto_20210327_1454"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "shipping",
                    models.DecimalField(decimal_places=2, default=10, max_digits=3),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ecommerce.cart"
                    ),
                ),
            ],
        ),
    ]
