# Generated by Django 3.1.4 on 2021-03-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20210314_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shirt_size',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoe_size',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.TextField(blank=True, choices=[('WHITE', 'white'), ('BLACK', 'black'), ('BLUE', 'blue'), ('GREEN', 'green')], max_length=10, null=True),
        ),
    ]
